---
- name: Firewalld 및 필수 유틸리티 설치
  dnf:
    name:
      - firewalld
      - curl
      - tar
      - nfs-utils
    state: present

- name: Firewalld 서비스 활성화 및 시작
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: .bashrc에 kubectl alias 추가
  blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: kubectl alias"
    block: |
      alias k='kubectl'
      source <(kubectl completion bash)
      complete -o default -F __start_kubectl k