[infra]
infra-node.orb.local

[k3s_master]
master-node.orb.local

[k3s_worker]
worker-node.orb.local

[k3s_cluster:children]
k3s_master
k3s_worker

[all:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.orbstack/ssh/id_ed25519
ansible_user=eumhwiyeong