---
- name: Shared Home 디렉토리 생성
  file:
    path: /data/shared-home/jira-shared-home
    state: directory
    mode: '0777'

- name: NFS Export 설정 적용
  lineinfile:
    path: /etc/exports
    line: "/data/shared-home/jira-shared-home *(rw,sync,no_root_squash)"
    state: present
  notify: Restart NFS

- name: 방화벽 개방 (NFS, RPC-Bind, Mountd)
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - nfs
    - rpc-bind
    - mountd